all: prova clean

file1.o: file1.c
	gcc -fPIC -g -c -Wall file1.c

file2.o: file2.c
	gcc -fPIC -g -c -Wall file2.c

prova: file1.o file2.o
	gcc -shared -Wl,-soname,libprova.so.1 -o libprova.so.1.0.1 file1.o file2.o -lc

clean: 
	rm ./*.o  ./*~
